ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
        watch:
            - classes
    development: true
database:
    url: "jdbc:postgresql://localhost:5432/students_db"
    driver: "org.postgresql.Driver"
    user: "main"
    password: "example"
